<?php

namespace App\Http\Resources;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class DoctorAvailableScheduleResource extends JsonResource
{
    private ?array $data;
    private string $message;
    private int $statusCode;

    public function __construct(?array $data, string $message, int $statusCode = 200)
    {
        $this->data = $data;
        $this->message = $message;
        $this->statusCode = $statusCode;
        parent::__construct($data);
    }

    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
       return [
           'data' => $this->data,
           'message' => $this->message,
       ];
    }
    public function withResponse(Request $request, JsonResponse $response): void
    {
        $response->setStatusCode($this->statusCode);
        parent::withResponse($request, $response); // TODO: Change the autogenerated stub
    }
}
